# Generated by Django 3.0.1 on 2020-01-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('pro_type', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField()),
                ('username', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 't_projects',
            },
        ),
    ]
