# Generated by Django 3.0.1 on 2019-12-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('user_id', models.CharField(default='', max_length=50)),
                ('create_time', models.DateTimeField()),
                ('last_login_time', models.DateTimeField()),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
